// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Afomiat/Digital-IMCI/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ClassificationRepository is an autogenerated mock type for the ClassificationRepository type
type ClassificationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, classification
func (_m *ClassificationRepository) Create(ctx context.Context, classification *domain.Classification) error {
	ret := _m.Called(ctx, classification)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Classification) error); ok {
		r0 = rf(ctx, classification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByAssessmentID provides a mock function with given fields: ctx, assessmentID
func (_m *ClassificationRepository) GetByAssessmentID(ctx context.Context, assessmentID uuid.UUID) (*domain.Classification, error) {
	ret := _m.Called(ctx, assessmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByAssessmentID")
	}

	var r0 *domain.Classification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Classification, error)); ok {
		return rf(ctx, assessmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Classification); ok {
		r0 = rf(ctx, assessmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Classification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, assessmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, classification
func (_m *ClassificationRepository) Upsert(ctx context.Context, classification *domain.Classification) error {
	ret := _m.Called(ctx, classification)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Classification) error); ok {
		r0 = rf(ctx, classification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClassificationRepository creates a new instance of ClassificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClassificationRepository {
	mock := &ClassificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
