// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Afomiat/Digital-IMCI/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MedicalProfessionalAnswerRepository is an autogenerated mock type for the MedicalProfessionalAnswerRepository type
type MedicalProfessionalAnswerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, answer
func (_m *MedicalProfessionalAnswerRepository) Create(ctx context.Context, answer *domain.MedicalProfessionalAnswer) error {
	ret := _m.Called(ctx, answer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MedicalProfessionalAnswer) error); ok {
		r0 = rf(ctx, answer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByAssessmentID provides a mock function with given fields: ctx, assessmentID
func (_m *MedicalProfessionalAnswerRepository) GetByAssessmentID(ctx context.Context, assessmentID uuid.UUID) (*domain.MedicalProfessionalAnswer, error) {
	ret := _m.Called(ctx, assessmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByAssessmentID")
	}

	var r0 *domain.MedicalProfessionalAnswer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.MedicalProfessionalAnswer, error)); ok {
		return rf(ctx, assessmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.MedicalProfessionalAnswer); ok {
		r0 = rf(ctx, assessmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MedicalProfessionalAnswer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, assessmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, answer
func (_m *MedicalProfessionalAnswerRepository) Update(ctx context.Context, answer *domain.MedicalProfessionalAnswer) error {
	ret := _m.Called(ctx, answer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MedicalProfessionalAnswer) error); ok {
		r0 = rf(ctx, answer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: ctx, answer
func (_m *MedicalProfessionalAnswerRepository) Upsert(ctx context.Context, answer *domain.MedicalProfessionalAnswer) error {
	ret := _m.Called(ctx, answer)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.MedicalProfessionalAnswer) error); ok {
		r0 = rf(ctx, answer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMedicalProfessionalAnswerRepository creates a new instance of MedicalProfessionalAnswerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMedicalProfessionalAnswerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MedicalProfessionalAnswerRepository {
	mock := &MedicalProfessionalAnswerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
