// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Afomiat/Digital-IMCI/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TreatmentPlanRepository is an autogenerated mock type for the TreatmentPlanRepository type
type TreatmentPlanRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, plan
func (_m *TreatmentPlanRepository) Create(ctx context.Context, plan *domain.TreatmentPlan) error {
	ret := _m.Called(ctx, plan)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TreatmentPlan) error); ok {
		r0 = rf(ctx, plan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByAssessmentID provides a mock function with given fields: ctx, assessmentID
func (_m *TreatmentPlanRepository) GetByAssessmentID(ctx context.Context, assessmentID uuid.UUID) ([]*domain.TreatmentPlan, error) {
	ret := _m.Called(ctx, assessmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByAssessmentID")
	}

	var r0 []*domain.TreatmentPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.TreatmentPlan, error)); ok {
		return rf(ctx, assessmentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.TreatmentPlan); ok {
		r0 = rf(ctx, assessmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TreatmentPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, assessmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTreatmentPlanRepository creates a new instance of TreatmentPlanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTreatmentPlanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TreatmentPlanRepository {
	mock := &TreatmentPlanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
